apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-backend
spec:
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-backend
  type: {{ .Values.backend.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-frontend
  type: {{ .Values.frontend.service.type }}
