apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-idp-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Perera1325/tourism-platform.git'
    targetRevision: HEAD
    path: helm/idp-platform
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: devsecops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
