apiVersion: v1
kind: Service
metadata:
  name: wso2is-service
  namespace: wso2
  labels:
    app: wso2is
spec:
  ports:
    - name: servlet-http
      port: 9763
      targetPort: 9763
    - name: servlet-https
      port: 9443
      targetPort: 9443
  selector:
    app: wso2is
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wso2is
  namespace: wso2
spec:
  serviceName: wso2is-service
  replicas: 1
  selector:
    matchLabels:
      app: wso2is
  template:
    metadata:
      labels:
        app: wso2is
    spec:
      containers:
        - name: wso2is
          image: wso2/wso2is:6.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9763
            - containerPort: 9443
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://devsecops-idp-db.c123456789.us-east-1.rds.amazonaws.com:5432/wso2shared"
            - name: DATABASE_USER
              value: "wso2admin"
            - name: DATABASE_PASSWORD
              value: "WSO2devsecopsPassword2026!"
          readinessProbe:
            tcpSocket:
              port: 9443
            initialDelaySeconds: 80
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9443
            initialDelaySeconds: 110
            periodSeconds: 15
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wso2is-ingress
  namespace: wso2
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: is.wso2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wso2is-service
                port:
                  number: 9443
